apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- istio-operator.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml
- gateway.yaml
- telemetries.yaml
- kiali-server.yaml
- mutual-mtls.yaml
- waypoint.yaml
