apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: shared-waypoint
    istio.io/use-waypoint-namespace: istio-system
