apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux
spec:
  interval: 10m0s
  path: "./flux/prometheus/yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  dependsOn:
  - name: kubernetes-secret-generator
