apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: prometheus
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/secure: "yes"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: admin