
apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app: bedrock
data:
  UID: "1000"
  GID: "1000"
  TZ: America/Detroit
  EULA: "TRUE"
  GAMEMODE: "creative"
  VIEW_DISTANCE: "20"
  TICK_DISTANCE: "4"
  MAX_THREADS: "8"
  ALLOW_CHEATS: "true"
  SERVER_NAME: "KID"
  # https://minecraft.wiki/w/Bedrock_Edition_version_history
  VERSION: "1.21.101.1"
  ONLINE_MODE: "false"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app: bedrock
spec:
  storageClassName: openebs-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bedrock
  name: bedrock
  namespace: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bedrock
  template:
    metadata:
      labels:
        app: bedrock
    spec:
      containers:
      - name: main
        image: itzg/minecraft-bedrock-server
        securityContext:
          runAsUser: 1000
        imagePullPolicy: Always
        resources:
          limits:
            memory: 6Gi
            cpu: 2
        envFrom:
        - configMapRef:
            name: bedrock
        volumeMounts:
        - mountPath: /data
          name: data
        ports:
        - containerPort: 19132
          protocol: UDP
          name: bedrock
        readinessProbe: &probe
          exec:
            command:
              - mc-monitor
              - status-bedrock
              - --host
              # force health check against IPv4 port
              - 127.0.0.1
          initialDelaySeconds: 30
        livenessProbe: *probe
        tty: true
        stdin: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bedrock
---
apiVersion: v1
kind: Service
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app: bedrock
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.14
spec:
  selector:
    app: bedrock
  ports:
  - port: 19132
    protocol: UDP
    name: bedrock
  type: LoadBalancer