apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux
- metallb
- prometheus
- cert-manager
- ddns-route53
- cpu-requests-remover-webhook
- openebs
- charts.yaml
- helmrepos.yaml
- istio-kustomization.yaml
- public-ip-configmapper
- minecraft
- coredns
- matchering
- package-tracker
- kubernetes-secrets-generator.yaml
- oauth2-proxy
- keycloak
- external-dns
- otterwiki
- k8up
- wordpress
