apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux
- metallb
- prometheus
- cert-manager
- ddns-route53
- cpu-requests-remover-webhook
- openebs
- charts.yaml
- helmrepos.yaml
- istio-kustomization.yaml
- wp-kustomization.yaml
- public-ip-configmapper
- minecraft
- coredns
- matchering
- package-tracker
