apiVersion: v1
kind: Namespace
metadata:
  name: package-tracker
  labels:
    # istio-injection: enabled
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    # istio.io/use-waypoint-namespace: istio-system
