apiVersion: v1
kind: Secret
metadata:
  name: package-tracker
  namespace: package-tracker
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/autogenerate: CSRF_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-tracker
  namespace: package-tracker
spec:
  selector:
    matchLabels:
      app: package-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: package-tracker
    spec:
      containers:
      - name: package-tracker
        image: bentastic27/package-tracker:0.0.7
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        env:
        - name: VALKEY_HOST
          value: valkey.package-tracker.svc.cluster.local
        - name: VALKEY_PORT
          value: "6379"
        - name: WEB_CONCURRENCY
          value: "2"
        - name: CSRF_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: package-tracker
              key: CSRF_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: package-tracker
  namespace: package-tracker
  labels:
    istio.io/ingress-use-waypoint: "true"
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: package-tracker